---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: deploy centos-job
  namespace: aap
spec:
  connection_secret: aapaccess
  job_template_name: VM_provisioning @ CentOS
  extra_vars: 